"""baseline 16 tables

Revision ID: 88c640d9032f
Revises: 
Create Date: 2026-09-07 22:12:07.465292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '88c640d9032f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_entities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('legal_name', sa.String(length=300), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('pincode', sa.String(length=10), nullable=True),
    sa.Column('gstin', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_entities_legal_name'), 'business_entities', ['legal_name'], unique=False)
    op.create_table('field_definitions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('canonical_key', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('data_type', sa.String(length=50), nullable=False),
    sa.Column('allowed_units', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_mandatory', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_field_definitions_canonical_key'), 'field_definitions', ['canonical_key'], unique=True)
    op.create_table('roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('permissions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('rule_sets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('version', sa.String(length=30), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('effective_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rule_sets_version'), 'rule_sets', ['version'], unique=True)
    op.create_table('brands',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('business_entity_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['business_entity_id'], ['business_entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brands_name'), 'brands', ['name'], unique=False)
    op.create_table('requirements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('rule_set_id', sa.UUID(), nullable=False),
    sa.Column('rule_ref', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('applicable_to', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('check_logic', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['rule_set_id'], ['rule_sets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_requirements_rule_ref'), 'requirements', ['rule_ref'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('employee_id', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_employee_id'), 'users', ['employee_id'], unique=True)
    op.create_table('audit_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('old_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_action'), 'audit_events', ['action'], unique=False)
    op.create_index(op.f('ix_audit_events_entity_id'), 'audit_events', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_events_entity_type'), 'audit_events', ['entity_type'], unique=False)
    op.create_table('commodities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('brand_id', sa.UUID(), nullable=True),
    sa.Column('business_entity_id', sa.UUID(), nullable=True),
    sa.Column('generic_name', sa.String(length=300), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('barcode', sa.String(length=100), nullable=True),
    sa.Column('sku', sa.String(length=100), nullable=True),
    sa.Column('package_type', sa.String(length=50), nullable=False),
    sa.Column('standard_pack_size', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('standard_pack_unit', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.ForeignKeyConstraint(['business_entity_id'], ['business_entities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commodities_barcode'), 'commodities', ['barcode'], unique=True)
    op.create_index(op.f('ix_commodities_category'), 'commodities', ['category'], unique=False)
    op.create_index(op.f('ix_commodities_generic_name'), 'commodities', ['generic_name'], unique=False)
    op.create_table('assignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('commodity_id', sa.UUID(), nullable=False),
    sa.Column('assigned_by', sa.UUID(), nullable=False),
    sa.Column('assigned_to', sa.UUID(), nullable=False),
    sa.Column('rule_set_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['commodity_id'], ['commodities.id'], ),
    sa.ForeignKeyConstraint(['rule_set_id'], ['rule_sets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assignments_status'), 'assignments', ['status'], unique=False)
    op.create_table('inspections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('assignment_id', sa.UUID(), nullable=True),
    sa.Column('commodity_id', sa.UUID(), nullable=False),
    sa.Column('officer_id', sa.UUID(), nullable=False),
    sa.Column('rule_set_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('compliance_result', sa.String(length=20), nullable=True),
    sa.Column('final_decision', sa.String(length=40), nullable=True),
    sa.Column('location', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('context_notes', sa.Text(), nullable=True),
    sa.Column('physical_quantity', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('physical_unit', sa.String(length=20), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finalized_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignments.id'], ),
    sa.ForeignKeyConstraint(['commodity_id'], ['commodities.id'], ),
    sa.ForeignKeyConstraint(['officer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['rule_set_id'], ['rule_sets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inspections_status'), 'inspections', ['status'], unique=False)
    op.create_table('analysis_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('inspection_id', sa.UUID(), nullable=False),
    sa.Column('pipeline_version', sa.String(length=50), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('raw_ocr_output', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_runs_status'), 'analysis_runs', ['status'], unique=False)
    op.create_table('compliance_evaluations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('inspection_id', sa.UUID(), nullable=False),
    sa.Column('requirement_id', sa.UUID(), nullable=False),
    sa.Column('result', sa.String(length=20), nullable=False),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('eval_detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evidence',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('inspection_id', sa.UUID(), nullable=False),
    sa.Column('file_key', sa.Text(), nullable=False),
    sa.Column('file_url', sa.Text(), nullable=True),
    sa.Column('view_type', sa.String(length=50), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('pdp_area_cm2', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('image_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('inspection_id', sa.UUID(), nullable=False),
    sa.Column('file_key', sa.Text(), nullable=False),
    sa.Column('file_url', sa.Text(), nullable=True),
    sa.Column('report_format', sa.String(length=20), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('generated_by', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['generated_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('inspection_id')
    )
    op.create_table('declarations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('inspection_id', sa.UUID(), nullable=False),
    sa.Column('analysis_run_id', sa.UUID(), nullable=True),
    sa.Column('evidence_id', sa.UUID(), nullable=True),
    sa.Column('field_definition_id', sa.UUID(), nullable=False),
    sa.Column('machine_value', sa.Text(), nullable=True),
    sa.Column('officer_value', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('confidence_label', sa.String(length=20), nullable=True),
    sa.Column('bounding_box', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('font_size_mm', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('font_family', sa.String(length=100), nullable=True),
    sa.Column('contrast_pass', sa.Boolean(), nullable=True),
    sa.Column('script_language', sa.String(length=50), nullable=True),
    sa.Column('clearance_pass', sa.Boolean(), nullable=True),
    sa.Column('is_corrected', sa.Boolean(), nullable=False),
    sa.Column('correction_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['analysis_run_id'], ['analysis_runs.id'], ),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ),
    sa.ForeignKeyConstraint(['field_definition_id'], ['field_definitions.id'], ),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('findings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('inspection_id', sa.UUID(), nullable=False),
    sa.Column('compliance_evaluation_id', sa.UUID(), nullable=False),
    sa.Column('evidence_id', sa.UUID(), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('legal_reference', sa.String(length=100), nullable=False),
    sa.Column('officer_accepted', sa.Boolean(), nullable=True),
    sa.Column('officer_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['compliance_evaluation_id'], ['compliance_evaluations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], ),
    sa.ForeignKeyConstraint(['inspection_id'], ['inspections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('findings')
    op.drop_table('declarations')
    op.drop_table('reports')
    op.drop_table('evidence')
    op.drop_table('compliance_evaluations')
    op.drop_index(op.f('ix_analysis_runs_status'), table_name='analysis_runs')
    op.drop_table('analysis_runs')
    op.drop_index(op.f('ix_inspections_status'), table_name='inspections')
    op.drop_table('inspections')
    op.drop_index(op.f('ix_assignments_status'), table_name='assignments')
    op.drop_table('assignments')
    op.drop_index(op.f('ix_commodities_generic_name'), table_name='commodities')
    op.drop_index(op.f('ix_commodities_category'), table_name='commodities')
    op.drop_index(op.f('ix_commodities_barcode'), table_name='commodities')
    op.drop_table('commodities')
    op.drop_index(op.f('ix_audit_events_entity_type'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_entity_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_action'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_users_employee_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_requirements_rule_ref'), table_name='requirements')
    op.drop_table('requirements')
    op.drop_index(op.f('ix_brands_name'), table_name='brands')
    op.drop_table('brands')
    op.drop_index(op.f('ix_rule_sets_version'), table_name='rule_sets')
    op.drop_table('rule_sets')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_field_definitions_canonical_key'), table_name='field_definitions')
    op.drop_table('field_definitions')
    op.drop_index(op.f('ix_business_entities_legal_name'), table_name='business_entities')
    op.drop_table('business_entities')
    # ### end Alembic commands ###
